-- MySQL Script generated by MySQL Workbench
-- mer. 06 avril 2022 :35:50
-- Model: New Model    Version: .0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema laJolieBoiteACode
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema laJolieBoiteACode
-- -----------------------------------------------------
DROP DATABASE if EXISTS laJolieBoiteACode;
CREATE SCHEMA IF NOT EXISTS `laJolieBoiteACode` DEFAULT CHARACTER SET utf8 ;
USE `laJolieBoiteACode` ;
-- -----------------------------------------------------
-- Table `laJolieBoiteACode`.`prospect`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laJolieBoiteACode`.`prospect` (
  `idprospect` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `NSiret` VARCHAR(30) NOT NULL,
  `adressePostale` VARCHAR(255) NOT NULL,
  `codePostal` VARCHAR(45) NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL,
  `url` VARCHAR(45) NULL,
  PRIMARY KEY (`idprospect`),
  UNIQUE INDEX `idprospect_UNIQUE` (`idprospect` ASC) ,
  UNIQUE INDEX `NSiret_UNIQUE` (`NSiret` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laJolieBoiteACode`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laJolieBoiteACode`.`contact` (
  `idcontacct` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `poste` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `statut` TINYINT NULL,
  `prospect_idprospect` INT NOT NULL,
  PRIMARY KEY (`idcontacct`),
  UNIQUE INDEX `idcontact_UNIQUE` (`idcontacct` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  INDEX `fk_contact_prospect_idx` (`prospect_idprospect` ASC) ,
  CONSTRAINT `fk_contact_prospect`
    FOREIGN KEY (`prospect_idprospect`)
    REFERENCES `laJolieBoiteACode`.`prospect` (`idprospect`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laJolieBoiteACode`.`commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laJolieBoiteACode`.`commentaire` (
  `id.commentaire` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `auteur` VARCHAR(100) NOT NULL,
  `dateDeCreation` DATE NOT NULL,
  PRIMARY KEY (`id.commentaire`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laJolieBoiteACode`.`facture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laJolieBoiteACode`.`facture` (
  `idfacture` INT NOT NULL AUTO_INCREMENT,
  `dateFacture` VARCHAR(45) NOT NULL,
  `prospect_idprospect` INT NOT NULL,
  `personne_idcontact` INT NOT NULL,
  `NumeroFacture` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfacture`),
  INDEX `fk_facture_prospect_idx` (`prospect_idprospect` ASC) ,
  INDEX `fk_facture_personne_idx` (`personne_idcontact` ASC) ,
  UNIQUE INDEX `idfacture_UNIQUE` (`idfacture` ASC) ,
  UNIQUE INDEX `NumeroFacture_UNIQUE` (`NumeroFacture` ASC) ,
  CONSTRAINT `fk_facture_prospect`
    FOREIGN KEY (`prospect_idprospect`)
    REFERENCES `laJolieBoiteACode`.`prospect` (`idprospect`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facture_personne`
    FOREIGN KEY (`personne_idcontact`)
    REFERENCES `laJolieBoiteACode`.`contact` (`idcontacct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laJolieBoiteACode`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laJolieBoiteACode`.`utilisateur` (
  `idutilisateur` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `motDePasse` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idutilisateur`),
  UNIQUE INDEX `idutilisateur_UNIQUE` (`idutilisateur` ASC) ,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
